#!/usr/bin/env python
# -*- coding: utf-8 -*-
# generated by wxGlade 0.6.3 on Sat May  7 23:46:58 2011

import MS2601B
from MenuIDs import *
import wx

# begin wxGlade: extracode
# end wxGlade



class MainFrame(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: MainFrame.__init__
        kwds["style"] = wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        
        # Menu Bar
        self.menubar = wx.MenuBar()
        wxglade_tmp_menu = wx.Menu()
        wxglade_tmp_menu.Append(MENU_CALIBRATION_ALL, "All", "", wx.ITEM_NORMAL)
        wxglade_tmp_menu.Append(MENU_CALIBRATION_FREQUENCY, "Frequency", "", wx.ITEM_NORMAL)
        wxglade_tmp_menu.Append(MENU_CALIBRATION_LEVEL_1, "Level (1)", "", wx.ITEM_NORMAL)
        wxglade_tmp_menu.Append(MENU_CALIBRATION_LEVEL_2, "Level (2)", "", wx.ITEM_NORMAL)
        self.menubar.Append(wxglade_tmp_menu, "Calibration")
        self.SetMenuBar(self.menubar)
        # Menu Bar end
        self.statusbar = self.CreateStatusBar(1, 0)

        self.__set_properties()
        self.__do_layout()

        self.Bind(wx.EVT_MENU, self.menu_handler_calibrate_all, id=MENU_CALIBRATION_ALL)
        self.Bind(wx.EVT_MENU, self.menu_handler_calibrate_frequency, id=MENU_CALIBRATION_FREQUENCY)
        self.Bind(wx.EVT_MENU, self.menu_handler_calibrate_level_1, id=MENU_CALIBRATION_LEVEL_1)
        self.Bind(wx.EVT_MENU, self.menu_handler_calibrate_level_2, id=MENU_CALIBRATION_LEVEL_2)
        # end wxGlade
        self.ms2601b = MS2601B.MS2601B()

    def __set_properties(self):
        # begin wxGlade: MainFrame.__set_properties
        self.SetTitle("MS2601B GPIB control")
        self.statusbar.SetStatusWidths([-1])
        # statusbar fields
        statusbar_fields = ["Ready ..."]
        for i in range(len(statusbar_fields)):
            self.statusbar.SetStatusText(statusbar_fields[i], i)
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: MainFrame.__do_layout
        sizer = wx.BoxSizer(wx.VERTICAL)
        self.SetSizer(sizer)
        sizer.Fit(self)
        self.Layout()
        # end wxGlade

    def menu_handler_calibrate_all(self, event): # wxGlade: MainFrame.<event_handler>
        self.statusbar.SetStatusText("Starting calibration: ALL")
        self.ms2601b.start_calibration(self.ms2601b.CAL_MODES["ALL"])
        event.Skip()

    def menu_handler_calibrate_frequency(self, event): # wxGlade: MainFrame.<event_handler>
        self.statusbar.SetStatusText("Starting calibration: FREQ")
        self.ms2601b.start_calibration(self.ms2601b.CAL_MODES["FREQ"])
        event.Skip()

    def menu_handler_calibrate_level_1(self, event): # wxGlade: MainFrame.<event_handler>
        self.statusbar.SetStatusText("Starting calibration: LEVEL (1)")
        self.ms2601b.start_calibration(self.ms2601b.CAL_MODES["LEVEL (1)"])
        event.Skip()

    def menu_handler_calibrate_level_2(self, event): # wxGlade: MainFrame.<event_handler>
        self.statusbar.SetStatusText("Starting calibration: LEVEL (2)")
        self.ms2601b.start_calibration(self.ms2601b.CAL_MODES["LEVEL (2)"])
        event.Skip()

# end of class MainFrame


if __name__ == "__main__":
    app = wx.PySimpleApp(0)
    wx.InitAllImageHandlers()
    frame_1 = MainFrame(None, -1, "")
    app.SetTopWindow(frame_1)
    frame_1.Show()
    app.MainLoop()
